In [7]:
import numpy as np

In [90]:
a = np.random.randint( 0, 10, 5 )

In [91]:
a

array([3, 6, 8, 0, 1])

In [97]:
sorted( a )

[0, 1, 3, 6, 8]

In [99]:
np.percentile( a, 75 )

6.0

In [104]:
x = np.random.randint(1, 20, 20).reshape(4, 5)

In [105]:
x

array([[ 2,  7, 14, 17,  4],
       [19,  5,  8, 18,  6],
       [15,  6,  9,  5,  4],
       [ 4, 10, 12, 10, 12]])

In [106]:
np.corrcoef( x )

array([[ 1.        ,  0.12713551, -0.38553263,  0.49006471],
       [ 0.12713551,  1.        ,  0.53491383, -0.71569362],
       [-0.38553263,  0.53491383,  1.        , -0.82954582],
       [ 0.49006471, -0.71569362, -0.82954582,  1.        ]])

In [110]:
a = np.array( [1,5,32,6,4] )
b = np.array( [9,45,23,2,1] )

In [111]:
a

array([ 1,  5, 32,  6,  4])

In [112]:
b

array([ 9, 45, 23,  2,  1])

In [113]:
np.corrcoef( a, b )

array([[1.        , 0.23344807],
       [0.23344807, 1.        ]])