In [7]:
import numpy as np

In [13]:
a = np.random.randint( 0, 50, 10 )

In [15]:
b = np.random.randint( 0, 50, 10 )

In [16]:
print( a )
print( b )

[27  0 41 11 24 20 29 37 27 15]
[39 26 24 42 36 37 12 42  2 11]


In [17]:
a > b 

array([False, False,  True, False, False, False,  True, False,  True,
        True])